name: Update Commit Count

on:
  schedule:
    - cron: '0 0 * * *' # roda todo dia à meia-noite UTC (pode ajustar)
  push:
    branches:
      - main  # ou a branch que você quiser monitorar

jobs:
  update-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get commit count
        id: commits
        run: |
          COUNT=$(git rev-list --count HEAD)
          echo "commit_count=$COUNT" >> $GITHUB_OUTPUT

      - name: Update README with commit count
        run: |
          # Substitui o texto placeholder {{commit_count}} pelo número real
          sed -i "s/{{commit_count}}/${{ steps.commits.outputs.commit_count }}/g" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update commit count to ${{ steps.commits.outputs.commit_count }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
